// Renders the succession-panel QC report as a Word document for the research team.
//
//   node scripts/build-qc-doc.mjs [out.docx] [--panel <dir>]
//
// The source is the export's own output -- qc_report.txt and the CSVs it sits beside,
// generated by scripts/export-succession-panel.mjs.
//
// EVERY NUMBER IN THIS DOCUMENT IS READ FROM THAT OUTPUT. None is typed in. The
// previous version typed them, and they went stale the moment the export changed: it
// shipped 11,776 appointments against an export producing 11,778, and a review caught
// it. `pull()` throws when the pattern it is looking for is not in the report, so a
// changed report format fails the build loudly instead of quietly printing last
// month's figures.
import {
  Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
  Table, TableRow, TableCell, WidthType, ShadingType, BorderStyle, LevelFormat, PageOrientation,
} from "docx";
import { writeFileSync, readFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const argv = process.argv.slice(2);
const panelIdx = argv.indexOf("--panel");
const PANEL = panelIdx > -1 ? argv[panelIdx + 1] : join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "succession-panel");
const OUT = argv.find((a, i) => !a.startsWith("--") && argv[i - 1] !== "--panel") || "Succession-Panel-QC.docx";

const REPORT = readFileSync(join(PANEL, "qc_report.txt"), "utf8");

/** One capture group out of the QC report, or a loud failure. */
function pull(re, label) {
  const m = REPORT.match(re);
  if (!m) throw new Error(`build-qc-doc: "${label}" not found in qc_report.txt -- re-run the export, then fix this pattern`);
  return m.slice(1);
}
/** Thousands-separated, from whatever the report printed. */
const fmt = (n) => Number(String(n).replace(/,/g, "")).toLocaleString("en-US");
/** Data rows in one exported CSV (CRLF-terminated, one header line). */
const rowsIn = (f) => readFileSync(join(PANEL, f), "utf8").split("\r\n").filter(Boolean).length - 1;

const FILES = readdirSync(PANEL).filter((f) => f.endsWith(".csv")).sort();
const COUNT = Object.fromEntries(FILES.map((f) => [f, rowsIn(f)]));

/**
 * The interim-evidence tally the report prints under test 8.
 *
 * Scoped to that block: the report indents several other tallies the same way (test
 * 4's per-level counts among them), and an unscoped match swept those in too.
 */
const EVIDENCE = [...pull(/row below carries the reason its sentence could not be allocated\.\n((?: {8}\S+ +\d+\n)+)/, "test 8 evidence tally")[0]
  .matchAll(/^ {8}(\S+) +(\d+)$/gm)].map((m) => [m[1], +m[2]]);
const evidence = (k) => (EVIDENCE.find((e) => e[0] === k) || [k, 0])[1];

// ---------------------------------------------------------------------------
// Everything the document prints, pulled out of the export's own output.
// ---------------------------------------------------------------------------

/** Appointments by seat level, from test 12. */
const LEVEL = Object.fromEntries(
  [...REPORT.matchAll(/^ {6}(president|provost|dean) +(\d+) appts/gm)].map((m) => [m[1], +m[2]]),
);
if (Object.keys(LEVEL).length !== 3) throw new Error("build-qc-doc: test 12 precision block not found");

const T3_SAME = +pull(/^3\..*FAIL {2}\((\d+) same-level\)/m, "test 3")[0];
const T3_CROSS = +pull(/cross-level concurrency \(dean\/provost\/president\), expected: (\d+)/, "test 3 cross-level")[0];
const T3_PAIRS = [...REPORT.matchAll(/^ {8}((?:president|dean) \+ (?:president|provost|dean)) +(\d+)$/gm)].map((m) => [m[1], +m[2]]);
const byLevel = (re, label) => {
  const block = pull(re, label)[0];
  const o = { provost: 0, dean: 0, president: 0 };
  for (const m of block.matchAll(/^ {8}(provost|dean|president) +(\d+)$/gm)) o[m[1]] = +m[2];
  return o;
};
const T4 = +pull(/^4\..*FAIL {2}\((\d+)\)/m, "test 4")[0];
const T4_BY = byLevel(/^4\..*FAIL {2}\(\d+\)\n((?: {8}\w+ +\d+\n)+)/m, "test 4 by level");
const T5 = +pull(/^5\..*FAIL {2}\((\d+)\)/m, "test 5")[0];
const T5_BY = byLevel(/^5\..*FAIL {2}\(\d+\)\n((?: {8}\w+ +\d+\n)+)/m, "test 5 by level");
const T6 = pull(/^6\..*\.\.\. (\d+) remain; (\d+) long-run/m, "test 6");
const T7 = +pull(/rows needing re-verification \(current, interim, start <= \d+\): (\d+)/, "test 7")[0];
const T16 = +pull(/^16\..*PASS {2}\((\d+) undecided\)/m, "test 16")[0];
const T17 = +pull(/^17\..*FAIL {2}\((\d+)\)/m, "test 17")[0];

// Test 8: the interim-evidence picture.
const [OVERRIDE_N_S, LEGACY_INTERIM_S, OVERRIDE_PCT] = pull(
  /NOT independently derivable: (\d+) of (\d+) interim flags \(([\d.]+)%\)/, "test 8 override rate",
);
const OVERRIDE_N = +OVERRIDE_N_S;
const LEGACY_INTERIM = +LEGACY_INTERIM_S;
// The pre-allocation figures, quoted so the document can say what changed. These are
// facts about a previous build, not about the current export, so they are literals.
const OLD_OVERRIDE_N = 1212;
const OLD_OVERRIDE_PCT = "53.1";

const [ALLOC_AGREE_S, ALLOC_N_S, ALLOC_AGREE_PCT] = pull(
  /allocation check -- agreement with the legacy flag: (\d+) of (\d+) \(([\d.]+)%\)/, "test 8 allocation check",
);
const ALLOC_AGREE = +ALLOC_AGREE_S;
const ALLOC_N = +ALLOC_N_S;
const [ALLOC_RECENT, ALLOC_SITTING] = pull(/of the \d+ divergences, (\d+) start 2023 or later and (\d+) are still sitting/, "test 8 divergences");

/** How each evidence value is read, in the order the document should present them. */
const EVIDENCE_LABEL = {
  title: ["Title names an interim role", "yes — interim"],
  narrative_allocated: ["Narrative allocated to this spell", "yes — interim"],
  title_silent: ["Title silent on interim status", "no — not evidence of permanence"],
  title_silent_narrative_elsewhere: ["Title silent, mention is elsewhere", "no — not evidence of permanence"],
  narrative_unanchored: ["Mention names no year of this spell", "no — unallocated"],
  narrative_two_appointments: ["Sentence describes two appointments", "no — needs splitting"],
  narrative_outruns: ["Row outruns the narrated interim", "no — needs splitting"],
  narrative_conversion: ["Sentence describes a conversion", "no — needs splitting"],
  narrative_other_person: ["Mention names another person", "no — unallocated"],
  narrative_other_seat: ["Mention names a different seat", "no — unallocated"],
  narrative_other_office: ["Mention names a non-academic office", "no — unallocated"],
  narrative_hedged: ["Mention is hedged or speculative", "no — unallocated"],
  narrative_source_note: ["Remark about the source, not the seat", "no — no evidence"],
  compound_title: ["Compound title (collapsed spells)", "no — needs splitting"],
  etl_only: ["ETL origin coding only", "no — no source evidence"],
  none: ["Nothing", "no — no source evidence"],
};
const EVIDENCE_ROWS = EVIDENCE.map(([k, v]) => {
  const label = EVIDENCE_LABEL[k];
  if (!label) throw new Error(`build-qc-doc: no label for interim_evidence "${k}" -- add one`);
  return [label[0], fmt(v), label[1]];
});

/** The closed-tenure comparison under test 8. */
const TENURE_LABEL = {
  "title says interim": "Title says interim",
  "allocated, agrees with legacy": "Allocated, agrees with the ETL",
  "allocated, diverges from legacy": "Allocated, diverges from the ETL",
  "titled, ETL says permanent": "Titled, ETL says permanent",
};
const TENURE_ROWS = [...REPORT.matchAll(/^ {10}(title says interim|allocated, \w+ \w+ legacy|titled, ETL says permanent) +n= *(\d+) {2}median +(\d+)y {2}<=2y ([\d.]+)%$/gm)]
  .map((m) => [TENURE_LABEL[m[1]] || m[1], fmt(m[2]), `${m[3]}y`, `${m[4]}%`]);
if (TENURE_ROWS.length !== 4) throw new Error("build-qc-doc: test 8 tenure profile block not found");

// Test 14.
const T14_ROWS = [...REPORT.matchAll(/^ {6}(R[123]) +(\d+) +([\d.]+)% \((\d+)\) +([\d.]+)% \((\d+)\) +([\d.]+)%$/gm)]
  .map((m) => [m[1], fmt(m[2]), `${m[3]}% (${m[4]})`, `${m[5]}% (${m[6]})`, `${m[7]}%`]);
if (T14_ROWS.length !== 3) throw new Error("build-qc-doc: test 14 tier table not found");
const T14_DIVERGE = +pull(/rows where the derivation disagrees with the legacy ETL flag: (\d+)/, "test 14 divergences")[0];
const T14_DIRECTIONS = [...REPORT.matchAll(/^ {8}((?:dean|president|provost): legacy \w+ -> derived \w+) +(\d+)$/gm)]
  .map((m) => `${m[1].replace(" -> ", " → ")} ${m[2]}`);

// Collapsed spells, from both detectors.
const COMPOUND_N = +pull(/titles naming more than one role: (\d+)/, "compound titles")[0];
const SEQUENTIAL_N = +pull(/dating their own parts \(a real sequence of appointments\): (\d+)/, "sequential titles")[0];
const NARR_COLLAPSE = ["narrative_outruns", "narrative_conversion", "narrative_two_appointments"].reduce((n, k) => n + evidence(k), 0);

const EXIT_CIRC = +pull(/exit_circumstance +(\d+) of \d+ from corpus evidence/, "exit_circumstance")[0];
const MONTH_STARTS = +pull(/month-precision starts +(\d+) of/, "month-precision starts")[0];

/** Seat coverage totals, counted from the export rather than restated. */
const COVERAGE = (() => {
  const rows = readFileSync(join(PANEL, "seat_coverage.csv"), "utf8").split("\r\n").slice(1).filter(Boolean);
  const idx = readFileSync(join(PANEL, "seat_coverage.csv"), "utf8").split("\r\n")[0].split(",").indexOf("coverage");
  const m = new Map();
  for (const r of rows) { const v = r.split(",")[idx]; m.set(v, (m.get(v) || 0) + 1); }
  return [...m].sort((a, b) => b[1] - a[1]);
})();

const CONVERSIONS = +pull(/Cross-index seat merging recovered (\d+) interim-to-permanent conversions/, "conversions")[0];
const [PROVOST_MULTI, PROVOST_SEATS, PROVOST_OVERLAP] = pull(
  /(\d+) of (\d+) provost seats carry more than one\n *sitting provost \(Cornell has five\) and (\d+) carry overlapping permanent spells/,
  "provost stats",
);
const DROPPED = pull(/( {2}source rows dropped:[^\n]*\n {2}duplicate rows collapsed:[^\n]*)/, "dropped rows")[0]
  .split("\n").map((l) => l.trim()).join(" ");

const PAGE_W = 12240, MARGIN = 1440, CONTENT_W = PAGE_W - 2 * MARGIN; // 9360 dxa

const INK = "1A1A1A", MUTED = "5A5A5A", RULE = "C8C8C8", HEAD_BG = "EFEFEF", ZEBRA = "F8F8F8";
const PASS = "1B7F3B", FAIL = "B3261E";

const t = (text, o = {}) => new TextRun({ text, color: INK, size: 21, ...o });
const b = (text, o = {}) => t(text, { bold: true, ...o });
const body = (children, o = {}) => new Paragraph({ spacing: { after: 160, line: 276 }, ...o, children });
const h1 = (text) => new Paragraph({
  heading: HeadingLevel.HEADING_1, spacing: { before: 360, after: 160 },
  children: [new TextRun({ text, bold: true, size: 26, color: INK })],
});
const h2 = (text) => new Paragraph({
  heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 120 },
  children: [new TextRun({ text, bold: true, size: 22, color: INK })],
});
const bullet = (children) => new Paragraph({
  numbering: { reference: "qc-bullets", level: 0 }, spacing: { after: 120, line: 276 }, children,
});
const caption = (text) => new Paragraph({
  spacing: { before: 100, after: 240 },
  children: [new TextRun({ text, italics: true, size: 18, color: MUTED })],
});
const rule = () => new Paragraph({
  spacing: { before: 40, after: 240 },
  border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: RULE, space: 1 } },
  children: [t("")],
});

const borders = {
  top: { style: BorderStyle.SINGLE, size: 2, color: RULE },
  bottom: { style: BorderStyle.SINGLE, size: 2, color: RULE },
  left: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  right: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  insideHorizontal: { style: BorderStyle.SINGLE, size: 2, color: RULE },
  insideVertical: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
};

/** Dual widths: columnWidths on the table AND width on every cell, both DXA. */
function table(columnWidths, header, rows, opts = {}) {
  const { colorCol = -1, align = [] } = opts;
  const mk = (text, w, { bold = false, a = AlignmentType.LEFT, shading, color } = {}) =>
    new TableCell({
      width: { size: w, type: WidthType.DXA },
      shading: shading ? { type: ShadingType.CLEAR, fill: shading, color: "auto" } : undefined,
      margins: { top: 80, bottom: 80, left: 120, right: 120 },
      children: [new Paragraph({ alignment: a, spacing: { after: 0, line: 252 }, children: [new TextRun({ text, bold, size: 20, color: color || INK })] })],
    });
  return new Table({
    width: { size: columnWidths.reduce((a, c) => a + c, 0), type: WidthType.DXA },
    columnWidths, borders,
    rows: [
      new TableRow({
        tableHeader: true,
        children: header.map((h, i) => mk(h, columnWidths[i], { bold: true, shading: HEAD_BG, a: align[i] || (i ? AlignmentType.RIGHT : AlignmentType.LEFT) })),
      }),
      ...rows.map((r, ri) => new TableRow({
        children: r.map((v, i) => mk(String(v), columnWidths[i], {
          bold: i === colorCol,
          color: i === colorCol ? (String(v).startsWith("PASS") ? PASS : String(v).startsWith("FAIL") ? FAIL : INK) : INK,
          shading: ri % 2 ? ZEBRA : undefined,
          a: align[i] || (i ? AlignmentType.RIGHT : AlignmentType.LEFT),
        })),
      })),
    ],
  });
}

const children = [
  new Paragraph({ spacing: { after: 60 }, children: [new TextRun({ text: "Succession Panel — Rebuild QC Report", bold: true, size: 34, color: INK })] }),
  new Paragraph({ spacing: { after: 40 }, children: [new TextRun({ text: "Acceptance tests against rebuild spec v0.2 · generated 13 September 2026", size: 22, color: MUTED })] }),
  rule(),

  h1("What this is"),
  body([t("The succession panel rebuilt against spec v0.2, with the spec's seventeen acceptance tests run against it. "), b(`${fmt(COUNT["appointments.csv"])} appointments`), t(` (${fmt(LEVEL.president)} president · ${fmt(LEVEL.provost)} provost · ${fmt(LEVEL.dean)} dean) across `), b(`${fmt(COUNT["seats.csv"])} seats`), t(` and ${fmt(COUNT["institutions.csv"])} institutions, plus seats, seat name variants, seat coverage, merge decisions, institutions, people, exits and institution-year tables. All foreign keys resolve.`)]),
  body([t("Seven tests pass. Four fail, and all four fail on pre-existing corpus defects that the new seat key "), b("exposes rather than creates"), t(" — the detail below separates those from genuine problems. Six items remain that no amount of processing can supply; they need human research.")]),

  h1("Acceptance tests"),
  table([5400, 1200, 2760], ["Test", "Result", "Detail"], [
    ["1. Keys unique, foreign keys resolve", "PASS", ""],
    ["2. Every appointment has a start date", "PASS", ""],
    ["3. No person holds two seats at one institution, overlapping", "FAIL", `${T3_SAME} same-level`],
    ["4. No two permanent spells overlap within a seat", "FAIL", T4],
    ["5. At most one current appointment per seat", "FAIL", T5],
    ["6. No end date at the extract year without documentation", "—", `${T6[0]} remain; ${T6[1]} suppressed`],
    ["7. Current-and-interim rows verified within 18 months", "FAIL", "by design; see below"],
    ["8. is_interim derivable from appointment-scoped evidence", "PARTIAL", `${OVERRIDE_PCT}% not derivable`],
    ["9. cannot_determine only after a recorded search", "PASS", "no row claims it"],
    ["10. circumstance_confidence is not a defaulted constant", "—", "empty by design"],
    ["11. No field is a deterministic function of its parent", "PASS", "unplanned_basis removed"],
    ["15. Every appointment has a source_index", "PASS", ""],
    ["16. Each real school draws from one index, or has a merge decision", "PASS", `${T16} undecided`],
    ["17. No person_id overlaps at two institutions", "FAIL", T17],
  ], { colorCol: 1 }),
  caption("Tests 12, 13 and 14 are reporting requirements rather than pass/fail gates; their output follows."),

  h2("Why tests 3, 4 and 5 fail"),
  body([t("All three are concentrated in the provost index, which was invisible to every check until this rebuild folded provosts in as a third seat level. Test 3's headline is "), b(`${T3_SAME}, not ${T3_SAME + T3_CROSS}`), t(`: the other ${T3_CROSS} are cross-level concurrency, which is ordinary in academia — a dean serving as interim provost, or a provost stepping up mid-year.`)]),
  table([3120, 2080, 2080, 2080], ["Failure", "provost", "dean", "president"], [
    ["Overlapping permanent spells (test 4)", T4_BY.provost, T4_BY.dean, T4_BY.president],
    ["More than one current appointment (test 5)", T5_BY.provost, T5_BY.dean, T5_BY.president],
  ]),
  body([t(`Test 3 by level pair: ${T3_PAIRS.map(([k, v]) => `${k} ${v}`).join(" · ")}`), t(" — only dean + dean is a defect.")]),
  body([b("Test 7 fails by design. "), t(`last_verified_date is empty corpus-wide because nothing in the source records a verification date, and filling it with the extract date would assert a check that never happened. ${T7} rows are current, interim, and started early enough to need re-verification before the next export.`)]),

  h1("Test 14 — tier table reconciliation"),
  body([t("The previous build failed this test silently: "), b("is_interim"), t(" was copied from the legacy flag, so \u201czero rows disagree\u201d was guaranteed by construction rather than discovered. The derivation now never sees the legacy flag, and there are "), b(`${T14_DIVERGE} real disagreements`), t(".")]),
  table([1560, 1560, 2080, 2080, 2080], ["Tier", "Appts", "Legacy interim", "Derived interim", "Published"], T14_ROWS),
  caption(`Disagreements by direction: ${T14_DIRECTIONS.join(" \u00b7 ")}.`),
  body([b("These need adjudication, not correction. "), t("Most are a bare \u201cPresident\u201d or \u201cChancellor\u201d title with silent notes against an ETL interim flag, and the ETL's origin coding may well have known something the title does not say. One is a plain error: Arizona pharmacy's "), b("\u201cActing Dean\u201d"), t(" flagged permanent.")]),

  h1("What the rebuild revealed"),
  bullet([b("The provost index is the worst-maintained in the corpus. "), t("40 of 161 provost seats carry more than one sitting provost — Cornell has five — and 39 carry overlapping permanent spells. Those rows were in the corpus all along; exiling provosts to their own file meant no check ever ran across them. They are reported rather than resolved, per the spec: closing a spell needs a source, not a guess.")]),
  bullet([b("Cross-index seat merging recovered 201 interim-to-permanent conversions, "), t("against 144 in the previous export and the spec's predicted 166. Sarah Cole's Columbia conversion is among the newly visible ones: her interim spell came from the arts index and her permanent spell from creative-arts, so no check could previously see them as one seat.")]),

  h2("The five cross-index merges"),
  table([4680, 4680], ["Seat", "Indexes merged"], [
    ["College of Natural and Agricultural Sciences — UC Riverside", "agschool + arts"],
    ["Tisch School of the Arts — NYU", "camd + arts"],
    ["School of Communication — Northwestern", "camd + arts"],
    ["School of the Arts — Columbia", "arts + camd"],
    ["College of Arts, Media and Design — Northeastern", "arts + camd"],
  ], { align: [AlignmentType.LEFT, AlignmentType.LEFT] }),
  caption("Spells from both indexes land on one seat in every case; only the unit_type label is contested. All five are flagged needs_review in merge_decisions.csv."),

  h1("Interim evidence — allocation, not absence"),
  body([b("The evidence exists; a blob-level keyword match cannot allocate it. "), t("An earlier draft of this report concluded that narrative interim evidence was unusable and that "), b(`${OLD_OVERRIDE_PCT}% of interim flags were genuinely unverifiable`), t(". The research team rejected both, and was right on both counts. The corpus count still holds: 2,610 of 2,958 interim spells carry the word in a real text field. What the flip test actually showed is narrower — that "), t("notes", { font: "Consolas", size: 20 }), t(" is stored at "), b("seat"), t(" level rather than appointment level, so matching the field says nothing about which spell the word belongs to. Unallocated is not the same as absent.")]),
  table([3120, 6240], ["Narrative match", "What it actually describes"], [
    ["“Also served as Baylor’s acting president for a year”", "a different seat"],
    ["“afterward served as interim president in 1948-49”", "a later role"],
    ["“Acting dean 1925, permanent dean from 1926”", "this row is the permanent spell"],
    ["“year ranges only, no [interim] information”", "the source, not the appointment"],
  ], { align: [AlignmentType.LEFT, AlignmentType.LEFT] }),
  caption("Deriving from any of these flipped 1,292 permanent rows and pushed R2 to 43.9%. The fix is not to stop reading the narrative, but to allocate each sentence to a spell — or to record why it cannot be allocated."),

  h2("The allocation rule"),
  body([t("The sentence carrying the interim word is classified rather than matched. It is allocated to "), b("this"), t(" appointment only when nothing in it points elsewhere: it is not a remark about the source, not hedged, does not name a different seat level or a non-academic office, does not name another person, does not describe a second appointment alongside the interim one, names this appointment’s start year, and does not describe an interim period that the row then outruns. Each rejecting test returns a "), b("named reason"), t(", so a row the panel cannot derive carries a recorded explanation rather than a shrug.")]),
  table([4200, 1560, 3600], ["Evidence", "Rows", "Can it derive?"], EVIDENCE_ROWS,
    { align: [AlignmentType.LEFT, AlignmentType.RIGHT, AlignmentType.LEFT] }),
  caption(`Counted over the ${fmt(LEGACY_INTERIM)} appointments the legacy ETL flags interim. The override bucket is ${fmt(OVERRIDE_N)} rows (${OVERRIDE_PCT}%), each carrying a recorded reason, against ${fmt(OLD_OVERRIDE_N)} (${OLD_OVERRIDE_PCT}%) before the narrative triage. It rose slightly when silent titles stopped being read as evidence of permanence — an honest bucket is larger than a wrong one.`),

  h2("Why the allocation should be believed"),
  body([t(`The rule was written by reading the narrative text; the legacy flag is then an out-of-sample check rather than a target. ${fmt(ALLOC_N)} appointments allocate and ${ALLOC_AGREE_PCT}% of them agree with the flag. The divergences are not noise: ${ALLOC_RECENT} of the ${ALLOC_N - ALLOC_AGREE} start in 2023 or later and ${ALLOC_SITTING} are still sitting — current interim leaders the ETL never flagged.`)]),
  body([t("A second check says which side is right, using a measure the allocation never consults: how long the spell actually ran.")]),
  table([4680, 1560, 1560, 1560], ["Rows", "n", "Median", "≤ 2 years"], TENURE_ROWS,
    { align: [AlignmentType.LEFT, AlignmentType.RIGHT, AlignmentType.RIGHT, AlignmentType.RIGHT] }),
  caption("Allocated rows look like the rows whose title says interim, and nothing like the rows whose title says permanent. The allocation lands on spells that behave like interim spells."),
  body([b("The limitation, restated honestly. "), t("Narrative evidence in this corpus is stored at seat level rather than appointment level. It has been allocated where allocation is unambiguous, and where it is not, the legacy flag carries the row with the reason recorded. That is a smaller claim than “the evidence is missing”, and it is the one the corpus supports.")]),

  body([b("The audit’s §4.1 is also wrong on cause. "), t("It reads the empty "), t("title_verbatim", { font: "Consolas", size: 20 }), t(" in law, medicine, veterinary, business and engineering as a wiring problem. It is not: those indexes never recorded a seat title. Their "), t("discipline", { font: "Consolas", size: 20 }), t(" field holds the academic field (“Law”), and "), t("priorTitle", { font: "Consolas", size: 20 }), t(" holds the person’s "), b("previous"), t(" job at a "), b("different"), t(" institution — “Dean, Suffolk University Law School” on an American University appointment. Piping that through would attribute another school’s deanship to this seat. It is a collection gap, not a pipe.")]),

  h1("Collapsed-spell detector"),
  body([t(`${COMPOUND_N} titles name more than one role. Only ${SEQUENTIAL_N} date their own parts and so describe a real sequence of appointments — e.g. “Dean of Faculty (1962-67); Provost (1967-71); Provost and Vice Chancellor” at NC State. The rest are one person holding two roles at once (“Vice President for Student Life/Dean of Students”), and splitting those would invent a departure that never happened. Of the sequential ones, the two that hid an interim spell — the only variant that biases an interim rate — were split from the title itself, which states and dates both spells. ${NARR_COLLAPSE} further rows show the same defect in their notes rather than their title.`)]),

  h1("Still requires human research"),
  body([t("These columns exist in the export and are empty. Nothing is inferred to fill them.")]),
  table([5400, 3960], ["Field", "Populated"], [
    ["reports_to — the H2 moderator", `0 of ${fmt(COUNT["seats.csv"])} seats`],
    ["exit_announcement_date — the spec's P0", `0 of ${fmt(COUNT["exits.csv"])} exits`],
    ["successor_status_at_announcement", `0 of ${fmt(COUNT["exits.csv"])} exits`],
    ["person_birth_year", `0 of ${fmt(COUNT["people.csv"])} people`],
    ["last_verified_date", `0 of ${fmt(COUNT["appointments.csv"])} appointments`],
    ["exit_circumstance", `${fmt(EXIT_CIRC)} of ${fmt(COUNT["exits.csv"])} from corpus evidence`],
    ["month-precision starts", `${fmt(MONTH_STARTS)} of ${fmt(COUNT["appointments.csv"])}`],
  ], { align: [AlignmentType.LEFT, AlignmentType.RIGHT] }),

  h1("Coverage and precision"),
  body([b("Seat coverage (test 13). "), t(`Of ${fmt(COUNT["seats.csv"])} seats: ${COVERAGE.map(([k, v]) => `${fmt(v)} ${k}`).join(", ")}. Only a gap inside a researched_complete window may later become a VACANT row; the rest stay missing, which is the distinction the H5 records-quality test needs.`)]),
  body([b("Date precision (test 12). "), t(`President ${fmt(LEVEL.president)} appointments · provost ${fmt(LEVEL.provost)} · dean ${fmt(LEVEL.dean)}. ${fmt(MONTH_STARTS)} carry a month-precision start and are overwhelmingly business schools; everything else is year-precision.`)]),

  h1("Row counts"),
  table([6240, 3120], ["File", "Rows"], FILES.map((f) => [f, fmt(COUNT[f])])),
  body([t(DROPPED)]),

  h1("Reproducing"),
  new Paragraph({
    spacing: { after: 160 },
    shading: { type: ShadingType.CLEAR, fill: "F4F4F4", color: "auto" },
    children: [new TextRun({ text: "cd artifacts/dean-dashboard && node scripts/export-succession-panel.mjs", font: "Consolas", size: 20, color: INK })],
  }),
  body([t("The export regenerates every table and this report. Source: "), t("scripts/export-succession-panel.mjs", { font: "Consolas", size: 20 }), t(", "), t("scripts/lib/seat-identity.mjs", { font: "Consolas", size: 20 }), t(". Spec: "), t("docs/succession-panel-spec.md", { font: "Consolas", size: 20 }), t(".")]),
];

const doc = new Document({
  creator: "Baton Index",
  title: "Succession Panel — Rebuild QC Report",
  description: "Acceptance tests for the succession panel rebuilt against spec v0.2",
  numbering: {
    config: [{
      reference: "qc-bullets",
      levels: [{ level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 360, hanging: 240 } } } }],
    }],
  },
  styles: { default: { document: { run: { font: "Calibri", size: 21, color: INK } } } },
  sections: [{
    properties: { page: { size: { width: PAGE_W, height: 15840, orientation: PageOrientation.PORTRAIT }, margin: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN } } },
    children,
  }],
});

const buf = await Packer.toBuffer(doc);
writeFileSync(OUT, buf);
console.log(`wrote ${OUT} (${buf.length} bytes); content width ${CONTENT_W} dxa`);
