// Renders the succession-panel QC report as a Word document for the research team.
//
// The source is succession-panel/qc_report.txt, generated by
// scripts/export-succession-panel.mjs. Nothing is recomputed here: if the numbers
// change, re-run the export and regenerate this.
import {
  Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
  Table, TableRow, TableCell, WidthType, ShadingType, BorderStyle, LevelFormat, PageOrientation,
} from "docx";
import { writeFileSync } from "node:fs";

const OUT = process.argv[2] || "Succession-Panel-QC.docx";
const PAGE_W = 12240, MARGIN = 1440, CONTENT_W = PAGE_W - 2 * MARGIN; // 9360 dxa

const INK = "1A1A1A", MUTED = "5A5A5A", RULE = "C8C8C8", HEAD_BG = "EFEFEF", ZEBRA = "F8F8F8";
const PASS = "1B7F3B", FAIL = "B3261E";

const t = (text, o = {}) => new TextRun({ text, color: INK, size: 21, ...o });
const b = (text, o = {}) => t(text, { bold: true, ...o });
const body = (children, o = {}) => new Paragraph({ spacing: { after: 160, line: 276 }, ...o, children });
const h1 = (text) => new Paragraph({
  heading: HeadingLevel.HEADING_1, spacing: { before: 360, after: 160 },
  children: [new TextRun({ text, bold: true, size: 26, color: INK })],
});
const h2 = (text) => new Paragraph({
  heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 120 },
  children: [new TextRun({ text, bold: true, size: 22, color: INK })],
});
const bullet = (children) => new Paragraph({
  numbering: { reference: "qc-bullets", level: 0 }, spacing: { after: 120, line: 276 }, children,
});
const caption = (text) => new Paragraph({
  spacing: { before: 100, after: 240 },
  children: [new TextRun({ text, italics: true, size: 18, color: MUTED })],
});
const rule = () => new Paragraph({
  spacing: { before: 40, after: 240 },
  border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: RULE, space: 1 } },
  children: [t("")],
});

const borders = {
  top: { style: BorderStyle.SINGLE, size: 2, color: RULE },
  bottom: { style: BorderStyle.SINGLE, size: 2, color: RULE },
  left: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  right: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  insideHorizontal: { style: BorderStyle.SINGLE, size: 2, color: RULE },
  insideVertical: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
};

/** Dual widths: columnWidths on the table AND width on every cell, both DXA. */
function table(columnWidths, header, rows, opts = {}) {
  const { colorCol = -1, align = [] } = opts;
  const mk = (text, w, { bold = false, a = AlignmentType.LEFT, shading, color } = {}) =>
    new TableCell({
      width: { size: w, type: WidthType.DXA },
      shading: shading ? { type: ShadingType.CLEAR, fill: shading, color: "auto" } : undefined,
      margins: { top: 80, bottom: 80, left: 120, right: 120 },
      children: [new Paragraph({ alignment: a, spacing: { after: 0, line: 252 }, children: [new TextRun({ text, bold, size: 20, color: color || INK })] })],
    });
  return new Table({
    width: { size: columnWidths.reduce((a, c) => a + c, 0), type: WidthType.DXA },
    columnWidths, borders,
    rows: [
      new TableRow({
        tableHeader: true,
        children: header.map((h, i) => mk(h, columnWidths[i], { bold: true, shading: HEAD_BG, a: align[i] || (i ? AlignmentType.RIGHT : AlignmentType.LEFT) })),
      }),
      ...rows.map((r, ri) => new TableRow({
        children: r.map((v, i) => mk(String(v), columnWidths[i], {
          bold: i === colorCol,
          color: i === colorCol ? (String(v).startsWith("PASS") ? PASS : String(v).startsWith("FAIL") ? FAIL : INK) : INK,
          shading: ri % 2 ? ZEBRA : undefined,
          a: align[i] || (i ? AlignmentType.RIGHT : AlignmentType.LEFT),
        })),
      })),
    ],
  });
}

const children = [
  new Paragraph({ spacing: { after: 60 }, children: [new TextRun({ text: "Succession Panel — Rebuild QC Report", bold: true, size: 34, color: INK })] }),
  new Paragraph({ spacing: { after: 40 }, children: [new TextRun({ text: "Acceptance tests against rebuild spec v0.2 · generated 13 September 2026", size: 22, color: MUTED })] }),
  rule(),

  h1("What this is"),
  body([t("The succession panel rebuilt against spec v0.2, with the spec's seventeen acceptance tests run against it. "), t("11,776 appointments"), t(" (2,706 president · 1,500 provost · 7,570 dean) across "), t("2,110 seats"), t(" and 459 institutions, plus seats, seat name variants, seat coverage, merge decisions, institutions, people, exits and institution-year tables. All foreign keys resolve.")]),
  body([t("Seven tests pass. Four fail, and all four fail on pre-existing corpus defects that the new seat key "), b("exposes rather than creates"), t(" — the detail below separates those from genuine problems. Six items remain that no amount of processing can supply; they need human research.")]),

  h1("Acceptance tests"),
  table([5400, 1200, 2760], ["Test", "Result", "Detail"], [
    ["1. Keys unique, foreign keys resolve", "PASS", ""],
    ["2. Every appointment has a start date", "PASS", ""],
    ["3. No person holds two seats at one institution, overlapping", "FAIL", "6 same-level"],
    ["4. No two permanent spells overlap within a seat", "FAIL", "73"],
    ["5. At most one current appointment per seat", "FAIL", "58"],
    ["6. No end date at the extract year without documentation", "—", "221 remain; 23 suppressed"],
    ["7. Current-and-interim rows verified within 18 months", "FAIL", "by design; see below"],
    ["8. is_interim derivable from appointment-scoped evidence", "PARTIAL", "53.1% unverifiable"],
    ["9. cannot_determine only after a recorded search", "PASS", "no row claims it"],
    ["10. circumstance_confidence is not a defaulted constant", "—", "empty by design"],
    ["11. No field is a deterministic function of its parent", "PASS", "unplanned_basis removed"],
    ["15. Every appointment has a source_index", "PASS", ""],
    ["16. Each real school draws from one index, or has a merge decision", "PASS", "0 undecided"],
    ["17. No person_id overlaps at two institutions", "FAIL", "41"],
  ], { colorCol: 1 }),
  caption("Tests 12, 13 and 14 are reporting requirements rather than pass/fail gates; their output follows."),

  h2("Why tests 3, 4 and 5 fail"),
  body([t("All three are concentrated in the provost index, which was invisible to every check until this rebuild folded provosts in as a third seat level. Test 3's headline is "), b("six, not 73"), t(": the other 67 are cross-level concurrency, which is ordinary in academia — a dean serving as interim provost, or a provost stepping up mid-year.")]),
  table([3120, 2080, 2080, 2080], ["Failure", "provost", "dean", "president"], [
    ["Overlapping permanent spells (test 4)", "39", "28", "4"],
    ["More than one current appointment (test 5)", "40", "17", "1"],
  ]),
  body([t("Test 3 by level pair: president + provost 29 · dean + provost 26 · dean + president 12 · "), b("dean + dean 6"), t(" — only the last is a defect.")]),
  body([b("Test 7 fails by design. "), t("last_verified_date is empty corpus-wide because nothing in the source records a verification date, and filling it with the extract date would assert a check that never happened. 29 rows are current, interim, and started in 2024 or earlier, so they need re-verification before the next export.")]),

  h1("Test 14 — tier table reconciliation"),
  body([t("The previous build failed this test silently: "), b("is_interim"), t(" was copied from the legacy flag, so \u201czero rows disagree\u201d was guaranteed by construction rather than discovered. The derivation now never sees the legacy flag, and there are "), b("27 real disagreements"), t(".")]),
  table([1560, 1560, 2080, 2080, 2080], ["Tier", "Appts", "Legacy interim", "Derived interim", "Published"], [
    ["R1", "741", "27.8% (206)", "27.7% (205)", "27.8%"],
    ["R2", "556", "27.9% (155)", "27.7% (154)", "27.9%"],
    ["R3", "633", "20.1% (127)", "17.7% (112)", "19.9%"],
  ]),
  caption("Disagreements: 21 president and 3 provost rows the ETL calls interim and a plain title calls permanent; 2 dean and 1 provost rows the reverse."),
  body([b("These need adjudication, not correction. "), t("Most are a bare \u201cPresident\u201d or \u201cChancellor\u201d title with silent notes against an ETL interim flag, and the ETL's origin coding may well have known something the title does not say. One is a plain error: Arizona pharmacy's "), b("\u201cActing Dean\u201d"), t(" flagged permanent.")]),

  h1("What the rebuild revealed"),
  bullet([b("The provost index is the worst-maintained in the corpus. "), t("40 of 161 provost seats carry more than one sitting provost — Cornell has five — and 39 carry overlapping permanent spells. Those rows were in the corpus all along; exiling provosts to their own file meant no check ever ran across them. They are reported rather than resolved, per the spec: closing a spell needs a source, not a guess.")]),
  bullet([b("Cross-index seat merging recovered 201 interim-to-permanent conversions, "), t("against 144 in the previous export and the spec's predicted 166. Sarah Cole's Columbia conversion is among the newly visible ones: her interim spell came from the arts index and her permanent spell from creative-arts, so no check could previously see them as one seat.")]),

  h2("The five cross-index merges"),
  table([4680, 4680], ["Seat", "Indexes merged"], [
    ["College of Natural and Agricultural Sciences — UC Riverside", "agschool + arts"],
    ["Tisch School of the Arts — NYU", "camd + arts"],
    ["School of Communication — Northwestern", "camd + arts"],
    ["School of the Arts — Columbia", "arts + camd"],
    ["College of Arts, Media and Design — Northeastern", "arts + camd"],
  ], { align: [AlignmentType.LEFT, AlignmentType.LEFT] }),
  caption("Spells from both indexes land on one seat in every case; only the unit_type label is contested. All five are flagged needs_review in merge_decisions.csv."),

  h1("Interim evidence — the audit\u2019s §3.2 and §4.1 both need correcting"),
  body([b("53.1% of interim flags cannot be independently verified"), t(", and that is a real limit rather than a filing error. The audit read the override rate as a misclassification and proposed reclassifying narrative evidence as derivation. Doing so and reading the matches shows why it cannot stand: "), t("notes"), t(" is not appointment-scoped.")]),
  table([3120, 6240], ["Narrative match", "What it actually describes"], [
    ["\u201cAlso served as Baylor\u2019s acting president for a year\u201d", "a different seat"],
    ["\u201cafterward served as interim president in 1948-49\u201d", "a later role"],
    ["\u201cActing dean 1925, permanent dean from 1926\u201d", "this row is the permanent spell"],
    ["\u201cyear ranges only, no [interim] information\u201d", "the source, not the appointment"],
  ], { align: [AlignmentType.LEFT, AlignmentType.LEFT] }),
  caption("Deriving from these flipped 1,292 permanent rows and pushed R2 to 43.9%. Derivation is therefore restricted to the title, which is appointment-scoped."),
  table([3120, 3120, 3120], ["Evidence", "Rows", "Can it derive?"], [
    ["Title names an interim role", "1,047", "yes — interim"],
    ["Title plain, notes silent", "24", "yes — permanent"],
    ["Narrative mention, unscoped", "929", "no"],
    ["ETL origin coding only", "195", "no"],
    ["Nothing", "84", "no"],
    ["Compound title (collapsed spells)", "4", "no — needs splitting"],
  ], { align: [AlignmentType.LEFT, AlignmentType.RIGHT, AlignmentType.LEFT] }),
  body([b("The audit\u2019s §4.1 is also wrong on cause. "), t("It reads the empty "), t("title_verbatim"), t(" in law, medicine, veterinary, business and engineering as a wiring problem. It is not: those indexes never recorded a seat title. Their "), t("discipline"), t(" field holds the academic field (\u201cLaw\u201d), and "), t("priorTitle"), t(" holds the person\u2019s "), b("previous"), t(" job at a "), b("different"), t(" institution \u2014 \u201cDean, Suffolk University Law School\u201d on an American University appointment. Piping that through would attribute another school\u2019s deanship to this seat. It is a collection gap, not a pipe.")]),

  h1("Collapsed-spell detector"),
  body([t("33 titles collapse several appointments into one row \u2014 29 of them provost rows, e.g. \u201cDean of Faculty (1962-67); Provost (1967-71); Provost and Vice Chancellor\u201d at NC State. Each deletes a conversion and biases the interim rate downward, which is the failure the two-row rule exists to prevent. They need splitting at source. This is now a standing check.")]),

  h1("Still requires human research"),
  body([t("These columns exist in the export and are empty. Nothing is inferred to fill them.")]),
  table([5400, 3960], ["Field", "Populated"], [
    ["reports_to — the H2 moderator", "0 of 2,110 seats"],
    ["exit_announcement_date — the spec's P0", "0 of 9,653 exits"],
    ["successor_status_at_announcement", "0 of 9,653 exits"],
    ["person_birth_year", "0 of 10,065 people"],
    ["last_verified_date", "0 of 11,776 appointments"],
    ["exit_circumstance", "92 of 9,653 from corpus evidence"],
    ["month-precision starts", "590 of 11,776"],
  ], { align: [AlignmentType.LEFT, AlignmentType.RIGHT] }),

  h1("Coverage and precision"),
  body([b("Seat coverage (test 13). "), t("Of 2,110 seats: 283 researched_complete, 394 researched_partial, 1,433 not_researched. Only a gap inside a researched_complete window may later become a VACANT row; the rest stay missing, which is the distinction the H5 records-quality test needs.")]),
  body([b("Date precision (test 12). "), t("President 2,706 appointments, all year-precision. Provost 1,500, of which 3 carry a month. Dean 7,570, of which 586 carry a month and 1 a day — and 585 of those are business schools.")]),

  h1("Row counts"),
  table([6240, 3120], ["File", "Rows"], [
    ["appointments.csv", "11,776"],
    ["exits.csv", "9,653"],
    ["institution_year.csv", "11,262"],
    ["people.csv", "10,065"],
    ["seat_name_variants.csv", "2,120"],
    ["seats.csv", "2,110"],
    ["seat_coverage.csv", "2,110"],
    ["institutions.csv", "459"],
    ["merge_decisions.csv", "5"],
  ]),
  body([t("Source rows dropped: 10,071 roster (no start date), 297 sub-dean, 191 not the chief-executive seat, 1,089 outside the Carnegie scope. 89 duplicate rows collapsed; 23 placeholder end dates suppressed.")]),

  h1("Reproducing"),
  new Paragraph({
    spacing: { after: 160 },
    shading: { type: ShadingType.CLEAR, fill: "F4F4F4", color: "auto" },
    children: [new TextRun({ text: "cd artifacts/dean-dashboard && node scripts/export-succession-panel.mjs", font: "Consolas", size: 20, color: INK })],
  }),
  body([t("The export regenerates every table and this report. Source: "), t("scripts/export-succession-panel.mjs", { font: "Consolas", size: 20 }), t(", "), t("scripts/lib/seat-identity.mjs", { font: "Consolas", size: 20 }), t(". Spec: "), t("docs/succession-panel-spec.md", { font: "Consolas", size: 20 }), t(".")]),
];

const doc = new Document({
  creator: "Baton Index",
  title: "Succession Panel — Rebuild QC Report",
  description: "Acceptance tests for the succession panel rebuilt against spec v0.2",
  numbering: {
    config: [{
      reference: "qc-bullets",
      levels: [{ level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 360, hanging: 240 } } } }],
    }],
  },
  styles: { default: { document: { run: { font: "Calibri", size: 21, color: INK } } } },
  sections: [{
    properties: { page: { size: { width: PAGE_W, height: 15840, orientation: PageOrientation.PORTRAIT }, margin: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN } } },
    children,
  }],
});

const buf = await Packer.toBuffer(doc);
writeFileSync(OUT, buf);
console.log(`wrote ${OUT} (${buf.length} bytes); content width ${CONTENT_W} dxa`);
